list: $/jonasgrunert/siketest/models/answer/columns.yaml
modelClass: JonasGrunert\Siketest\Models\Answer
title: Answer
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'jonasgrunert/siketest/answer/update/:id'
