list: $/jonasgrunert/aboutus/models/member/columns.yaml
modelClass: JonasGrunert\Aboutus\Models\Member
title: AboutUs_View
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    search:
        prompt: 'backend::lang.list.search_prompt'
