list: $/jonasgrunert/siketest/models/question/columns.yaml
modelClass: JonasGrunert\Siketest\Models\Question
title: Question
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'jonasgrunert/siketest/question/update/:id'
